### ISSUE TITLE
Add team members to readthedocs for this repo + change to python 3?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#107]
Hey @willingc - I noticed that our RTD build failed for team-compass because (I think) we're using Python 2.7, and the `run` function in the subprocess module wasn't introduced until sometime in 3.x. Could we start building the docs from 2.7 to make this work? (I feel like many projects are starting to default to python 3 so this may be a good idea anyway).

I also saw that the other team members aren't listed as admins on the repository...could you add me as well?

**Comment by willingc** [comment]
I added you and a few others.

I enabled Python3 in the admin UI since it was set to 2.7, and now it's building. We probably should add a `readthedocs.yml` file in the repo root so it takes precedence over the admin UI. 

We should make sure that we're using Python 3 for all doc builds since I don't think there is any dependencies that need 2.7 and if there is, we should update those :smile:

**Comment by choldgraf** [comment]
good call! and thank you :-)
