### ISSUE TITLE
recording monthly meetings?

### ISSUE THREAD

**Issue by lheagy** [jupyterhub/team-compass#116]
With some of the geophysics software I contribute to, we record our weekly meetings (using hangouts on air). It has been a valuable way for other potential contributors to start engaging with us, as they can get a sense of the project, meeting norms, etc passively before they actively jump in. There are on average ~20 people who watch our meetings each week (mostly asynchronously). Sometimes these is people who would normally attend, but are away at a conference (or similar). Many of them are people who just want to keep a pulse on the project and they periodically contact us afterwards with follow-up questions and ideas. 

This could be another item to add to #110 for in-person conversations at the meeting. 

(We actually started doing this after seeing the Jupyter meeting recordings several years ago - so bringing the idea full circle 😄)

**Comment by choldgraf** [comment]
I'm all for it - I believe that the calpoly zoom has some kind of recording feature, no?

**Comment by betatim** [comment]
I'm +-0 on this.

If someone knows how to setup and operate the tech required (when using zoom as the video conference tool): why not try it out at next weeks meeting already? I think there was never a complaint about recording the meetings it just stopped because no one was eager to do it -> we can bring it back without a big discussion and see what happens.

---

Personally I much prefer good written notes from a meeting that I couldn't attend to catch myself up or keep an eye on what is going on. Partly because the number one reason for missing a meeting is "not enough hours in the day" so having to watch the video to catch up takes about as much time as going to the meeting (yes you can 1.5x it ...). Also the video isn't indexed/searchable though I rarely do that.

**Comment by minrk** [comment]
The zoom we use does have such permissions, but it means that someone at the meeting must be logged in "as Jupyter" in order to use it (only the host/owner can record). This is typically Ana for the Jupyter meetings, but I or @willingc may have access to do so as well.

**Comment by choldgraf** [comment]
Riffing on what @betatim said, I think that we should prioritize taking and recording high-quality notes over videos. If we think videos will detract from the notes, then it wouldn't be worth it.

One question I have: are video recordings vs. notes seen as more or less accessible? That should be another thing that we optimize for when making our meetings available to the world

**Comment by Zsailer** [comment]
> we should prioritize taking and recording high-quality notes over videos
👍 agreed. 

That said, I've met people who said watching our past Jupyter team meetings videos made it *less* intimidating for them to interact with the core team. Before that, they'd be too shy to jump on a call (or even reach out over Github/gitter/etc.) without first seeing what a team meeting looks like or how the core members interact with each other. They'd see we're normal (or relatively normal 😉) people and feel comfortable to engage.

**Comment by lheagy** [comment]
> Riffing on what @betatim said, I think that we should prioritize taking and recording high-quality notes over videos. If we think videos will detract from the notes, then it wouldn't be worth it.

:+1: on making sure it doesn't detract from note-taking, but hopefully it is as simple as hitting a "record" button and then forgetting about it. If not, then we need to weigh this out. 

> One question I have: are video recordings vs. notes seen as more or less accessible? That should be another thing that we optimize for when making our meetings available to the world

I wouldn't necessarily frame this as an either or, hopefully the recording is an additional avenue for others to interact. I completely agree with @Zsailer's point about it being important for people to see that we are real people and not just github avatars 😄

**Comment by choldgraf** [comment]
👍 I didn't meant to say it was "either/or", just wanted to highlight that accessibility should be something we optimize for in making our materials available to others, but I'm not super well-versed on what makes something more or less accessible

**Comment by Zsailer** [comment]
Btw, I *think* Zoom has a feature for transcribing videos too. This wouldn't replace note-taking, but it might supplement it?

**Comment by betatim** [comment]
... and we are live in, five, four, three, ✌️, ☝️, ✊. Let's do it. Leah and/or Zach could you find out if/how we can grow the pool of possible recorders (so we can share it around and never end up having no one).

I also added a comment to the meeting agenda/issue.

**Comment by Zsailer** [comment]
@betatim Yup! I just talked to Ana (benefits of being in the same location :)).

She's going to give me recording privileges for next week, then we can discuss at next week's meeting the best way to increase this pool of people. There is some hesitation there, because the Zoom account is actually linked to Ana's Cal Poly email/identity. We may need to look into getting a Project Jupyter Cal Poly account.

**Comment by betatim** [comment]
We seem to be decided and have a few people who can do the recording. Let's close this and make a new issue if we need to discuss something else related to this topic.
