### ISSUE TITLE
JupyterLab 1.0 blog post traffic

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#177]
Hey all - I believe that sometime this weekend the JupyterLab team will release a blog post about JupyterLab 1.0. There's a good chance that this will send another spike of traffic towards mybinder.org, so we should prepare.

@jasongrout, can you confirm when this post would go live?

For the mybinder.org ops team, what do you think we should do about this? Raise the repository limit for a short time? Pre-cook some nodes so that we don't hit an outage?

**Comment by betatim** [comment]
Step one is find out which repo is going to be linked to from the blog post and if that will be the same as one as is linked from https://jupyter.org/try.

We should make sure it builds and launches on both GKE and OVH.

The limit is already 10-15% higher than 100 because the limit applies per cluster.

I am in two minds about raising the limit. Not sure we will hit the limit or not. It is a good carrot for someone to implement per repo limits in BinderHub and consistent with the message we have sent everyone else so far: we are happy to provide extra capacity for you, in return we need you to do something for us because if we start making exceptions, everyone will want us to make an exception for them.

**Comment by choldgraf** [comment]
Makes sense to me - IMO "releasing JupyterLab 1.0" is more than enough of a pay-back for raising the repo limit temporarily :-)  I agree with your general assessment about everybody wanting exceptions, but personally am happy to make exceptions for major milestones of major projects within the Jupyter community.
