### ISSUE TITLE
Add page with resources and guidelines for "giving talks and tutorials about the Binder project"

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#179]
I've started to notice that many folks are a little bit hesitant to give talks "on behalf of" the Binder Project (e.g. to talk about Binder for a significant part of their presentation). I think we should encourage others talking about the project as much as possible, provided that they say things that are in line with the project's best interests.

What do people think about a page in the team compass that has:

* A call to action that folks are welcome to incorporate overviews etc of Binder in their talks (or for all of their talk)
* A set of guidelines they should follow if they want to do so (things like make sure to thank the community, don't claim credit for things, say things in line with the CoC of the Jupyter Project, etc)
* A set of talk resources (slides, repositories, etc) for those who wish to give a presentation or tutorial

**Comment by betatim** [comment]
Some notes from the team meeting on this topic: https://github.com/jupyterhub/team-compass/blob/master/docs/monthly-meeting/2019-06-19.md

**Comment by choldgraf** [comment]
@betatim so it sounds like in general people were +1 on the idea? Are we +1 enough that it's worth starting a PR?

**Comment by betatim** [comment]
> Talking "About Binder" should be encouraged, even/especially by none team members

Meant that most people at the meeting who offered an opinion thought that talking about the past and current of Binder(Hub)/mybinder.org should be encouraged and was uncontroversial (the past is the past)

> Several people support having a collection of facts, figures, images, drawings, etc that help evangelise for Binder

This might be the most actionable. A collection of previous talks, as well as "original" images/drawings with a description of what to say about them. I think the latter is super useful because Google slides or PDF make terrible sources of images to re-use in a new talk (screenshot hell) and you don't know the words that go with it. For a lot of the basics (how does binder work? what is project binder? who is binder? standard&recent pic of the team, etc) we could come up with stock answers that people can re-use and we collectively tune. Like the intro in the docs etc. It makes our lives easier and we'd give outsiders stuff to use as well.

> A wiki post on discourse with frequently asked questions about mybinder.org direction and plans

Maybe a source of answer for the "basics" section mentioned above as well as a place for figuring out answers to questions about the future of Binder. Or at least writing down answers to questions about the future (when and if they are known).

It would also be good to hear from @KirstieJane who mentioned "[Somewhere to post slides] ... Maybe in advance of speaking? Just to double check if folks want to? I suspect more people would give the talks if they a) knew that would be helpful, b) had some to crib from/reuse, c) had a little safety net for someone to double check before they go on stage". Would a discourse thread work for this ("If you are giving a talk in the future and seeking feedback/clarification post slides in a new thread")? Too public? A standing agenda item for the team meeting? Too rare?
