### ISSUE TITLE
Tell me about your favourite grafana plots!

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#182]
Hey everyone!

I'm trying to improve the SRE guidelines for mybinder a bit and it was suggested that we have a section describing the grafana plots and what they show (see https://github.com/jupyterhub/team-compass/issues/180#issuecomment-507304437). If you could leave a comment with a link to your favourite grafana plot, a description of what it's showing and in what context you find it useful to check it, that would help me out a lot! Thank you!

**Comment by minrk** [comment]
The [launch/build success rate](https://grafana.mybinder.org/d/3SpLQinmk/1-overview?refresh=1m&orgId=1&var-cluster=default&panelId=16&fullscreen) is my favorite, as it's the main indicator that things are healthy. When there's something wrong, success rate dropping is the main indicator that it's hitting our users.

![Screen Shot 2019-07-02 at 13 08 08](https://user-images.githubusercontent.com/151929/60508276-76162380-9cca-11e9-8a96-5541a22e3865.png)

The caveat with this one as an indicator of current status: if builds or launches are failing due to timeouts, it can take a long time to show up here, as a launch failure is only reported when it's done failing. With retries, this can be several minutes.

**Comment by minrk** [comment]
Also a fan of [pods per node](https://grafana.mybinder.org/d/nDQPwi7mk/node-activity?orgId=1&var-cluster=prometheus&panelId=26&fullscreen), which shows us which nodes have all our users. This is a handy view that shows when it looks like auto-scaling might need a helping hand (e.g. a node has had very low load for a long time, it might want a manual cordon & drain because some pod is stuck on it).

![Screen Shot 2019-07-02 at 13 12 21](https://user-images.githubusercontent.com/151929/60508596-356ada00-9ccb-11e9-9d9e-9f2a9a609a17.png)

**Comment by betatim** [comment]
I look at https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?refresh=1m&panelId=3&fullscreen&orgId=1 because I (believe) to know what a typical number is that I should see there (10s of pods on OVH, 100s on GKE). I also lets me see if there is a sudden spike in pod numbers which tends to mean someone did something interesting like post a link on HackerNews or so and we will get a lot of a traffic (or got a lot of traffic if it was in the past).

I also look at https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?refresh=1m&panelId=9&fullscreen&orgId=1&var-cluster=prometheus for the same reason Min mentioned. I like that it shows me how many launch attempts there were. If there are none the success rate is also zero/no line. Having the launch attempts there helps me know if no one tried or people tried but failed. Sometimes huge spikes in launch attempts happen which is also interesting to investigate.

I also also look at https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?refresh=1m&panelId=1&fullscreen&orgId=1&var-cluster=prometheus because it tells me which repos are being launched. It is a bit weird to read the chart because at any moment in time it shows you how many launches there were in the previous 60minutes for that repo. So for a class that starts at 9am you'd see a step around 9am followed by a plateau corresponding to the class size. On [this particular snapshot](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?panelId=1&fullscreen&orgId=1&var-cluster=prometheus&from=1561999602689&to=1562086002689) you can see that there was probably some event relate to spacy (red ish line peaking at 11am), just before 10am something about neuroscience, the DS-100 textbook is an ever popular repo (I don't understand California students and their browsing habits), and https://bitbucket.org/nikiubel/nikiubel.bitbucket.io.git (green line all across the chart) is probably someone embedding the wrong link somewhere because that repo isn't a repo but it gets a lot of clicks with a pattern to it so maybe even a script??

**Comment by sgibson91** [comment]
> I look at https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?refresh=1m&panelId=3&fullscreen&orgId=1 because I (believe) to know what a typical number is that I should see there (10s of pods on OVH, 100s on GKE). I also lets me see if there is a sudden spike in pod numbers which tends to mean someone did something interesting like post a link on HackerNews or so and we will get a lot of a traffic (or got a lot of traffic if it was in the past).

Just to confirm what the values in the drop down menu are here:

* prometheus -> GKE
* OVH prometheus -> OVH
* default -> sum of both clusters?

**Comment by betatim** [comment]
> default -> sum of both clusters?

Don't think so. Either default is == prometheus or something else weird. I've never investigated what it is exactly.
