### ISSUE TITLE
August Team Meeting 2019

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#196]
Hello everyone, 

The August meeting will be happening next Thursday!
_(better late than never on the announcement 😄)_

That's **Thursday, August 15th, 2019** at 7AM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2019-08-15/07:00/Jupyterhub%2FBinder%20team%20meeting)). 

* Discourse post [here](https://discourse.jupyter.org/t/jupyterhub-community-call-august-2019/1861). 
* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)
* 🎥 🎬 we will record the meeting for those who can't make it.

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by betatim** [comment]
I'll be there.

**Comment by choldgraf** [comment]
I won't be able to make it due to the time, but I'll give an update in the notes beforehand!

**Comment by Zsailer** [comment]
Pinging here to remind those in Europe->Asia that our monthly JupyterHub Call is happening in ~15.5 hours. 😄

**Comment by rmorshea** [comment]
@kevin-bates, I won't be able to join, but if you do, feedback on https://github.com/ipython/traitlets/issues/530 and what belongs in a 4.3.3 Traitlets release would be great.

**Comment by kevin-bates** [comment]
Thanks @rmorshea - I'm unable to attend as well.  I just need a vehicle to carry the changes for https://github.com/ipython/traitlets/pull/532 and don't have an opinion on the others.  I will say that most of the other changes probably introduce or depend on changes that warrant an API change as I believe 5.0 has been in the works for a while.

Not sure why this would be part of the Hub discussion, but that's great if it is.

**Comment by rmorshea** [comment]
@kevin-bates I must have misunderstood the purpose of https://github.com/ipython/traitlets/pull/522 - I thought it had applications for admins.

I'm mostly just trying to get eyes on the release though because it's a critical part of the stack and there may be stakeholders who would be willing to contribute to 4.3.3 in order to get some long awaited feature from master.

**Comment by kevin-bates** [comment]
Ah - you're right, I think I had mentioned that Hub would be a good candidate for this since it's a long-running "service" and this PR paves the way toward dynamic configurations (further discussed in https://github.com/ipython/traitlets/pull/521).  

I think the plan would be to let something like Enterprise Gateway be the example case and go from there.  Since the community overlaps many projects, it would be awesome if there was interest from Hub such that the necessary momentum for a traitlets release could occur.

Another Hub use-case is that this could allow admins to potentially push config changes/updates to existing notebook instances w/o requiring restarts (given Notebook has the necessary hooks in place as well).
