### ISSUE TITLE
Costs and $$$ plans for mybinder.org

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#197]
Hey all - we are getting close to the end of our 1-year cloud credits from Google, which **will run out in December**.

We are currently spending credits at a rate of about $4,000 a month. Here is cloud costs over the last two years.

![image](https://user-images.githubusercontent.com/1839645/62971038-b1c20400-bdc5-11e9-98ed-cc8c8ad90194.png)

For an interactive version of the cost breakdown, I've updated the [`binder-billing` viz repository](https://github.com/jupyterhub/binder-billing) that shows plots of our costs. Use the nbviewer link below to check them out:

https://nbviewer.jupyter.org/github/jupyterhub/binder-billing/blob/master/analyze_data.ipynb?flush_cache=True

## Planning for the end of these credits

We should start planning for how to keep mybinder.org running once this round of credits runs out. I feel like we have a few different options:

1. Partner with Google again for another round of annual credits.
2. Partner with a *different* cloud provider for a round of annual credits.
3. Convince enough stakeholders to join the federation that we can fund this off of grants etc that we've already got
4. Run some kind of fundraising or donation campaign to fund mybinder.org's GKE deployment

What do folks think about these options? Anyone have ideas about one vs. another?

**Comment by betatim** [comment]
I have a preference for (1).

Even if we find lots of partners for (3) we'd need a home base for which my preference would be GKE because we have experience and a setup that works well. -> keep our foot on the gas for increasing the number of partners, this is a long term strategy.

I don't think (4) is realistic. I don't think there is a single large scale service that asks for donations and where donations are in the top three of income sources. I chatted with someone from PyPI, they receive individual "large" donations like $50 but they require a million per year to operate -> individual donations are nowhere near enough. Interesting article: https://dustingram.com/articles/2019/04/02/pypi-as-a-service/

**Comment by choldgraf** [comment]
closing this as we now have a new iteration of this challenge in #463 🙃
