### ISSUE TITLE
Use of PyUP

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#231]
https://pyup.io/ seem to help us bump our python dependencies for security, try it out for a repo or two? I volunteer oauthenticator ;D

**Comment by choldgraf** [comment]
It seems like a good idea to me - will it make the PRs for us automatically?

**Comment by consideRatio** [comment]
I dont know, i think so!

**Comment by betatim** [comment]
Doesn't GitHub already send us emails about dependencies that have security related updates pending? Based on what we have in our `requirements.txt` and `package.json` etc.

My feeling is that I already receive several vulnerability reports and that there are two scenarios: easy update (we do it) and hard to deal with (the version of xterm we use in BinderHub) in which case we don't do it. My impression is that in the repositories I care about I know what the insecure dependencies are but unless they are easy to deal with or super critical they don't get dealt with.

I'd be interested in exploring ideas that help us in the hard case. I am not sure if yet another tool/service will help with this :-/

**Comment by minrk** [comment]
Vulnerability reports and there-was-just-an-update PRs are slightly different. I think GitHub only does the vulnerability ones. We should be careful, however, to only apply this to frozen-dependency repos (i.e. images in charts, repo2docker) and not the dependencies of *packages* which are not and should not generally be pinned in Python, unlike javascript where everything is always pinned down.

I think one step is to adopt lockfiles (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1221) in all our image builds so that updates are easier to track/update explicitly. We do this in repo2docker base envs, but not anywhere else, I think.

**Comment by manics** [comment]
Is GitHub's dependabot a suitable replacement for pyup?

**Comment by manics** [comment]
Please re-open if this is still relevant.
