### ISSUE TITLE
December Team Meeting 2019

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#240]
Hello everyone, 

The December meeting will be on the _third_ Thursday of the month.

That's **Thursday, December 19th, 2019** at 7AM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2019-12-19/07:00/Jupyterhub%2FBinder%20team%20meeting)). 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by betatim** [comment]
I won't make it.

**Comment by minrk** [comment]
Not enough folks for a meeting, probably too close to the holidays, but @odontomachus from the Human Brain Project and I chatted a bit about deploying zero-to-jupyterhub on a cluster where you aren't a cluster admin and how helm 3's tiller-less design might help with that. He volunteered to look into helm 3 and z2jh a bit.

It looks like we already have an issue for that (jupyterhub/zero-to-jupyterhub-k8s#1497) and that at least some deployments need no changes. Upgrading *existing* deployments from helm 2 to 3 is the main area in need of testing and documentation.

**Comment by betatim** [comment]
@minrk and @odontomachus do you have a short summary of "deploy to cluster where you aren't admin"? I've been offered access to a k8s deployment run by https://www.cscs.ch/ where I am not only not admin but also share the cluster with other users. So I'd be interested in comparing notes and such. I haven't yet tried to deploy BinderHub or JupyterHub to that cluster, it is somewhere on my list of things to do once I catch up with the world after having been away.

**Comment by odontomachus** [comment]
Hi @betatim 
My use case is exactly that: to deploy on an ICD cluster at CSCS.
I don't have a working deployment there yet, but there are a few things I've needed to change to get near:

1. Disabled user scheduling and image pulling since they required elevated privileges.
2. Set a `USER <uid>` for jovyan on notebook images so that kubernetes can validate the security policy of must run as non root.

I had also managed to get tiller running in the same namespace with a service account, but I switched to helm 3 and so far I've been able to deploy the 0.9-beta versions of the helm chart without tiller, so it looks quite promising.

I am quite glad to compare notes and document this a bit better.
