### ISSUE TITLE
Consider migrating GKE nodes to the new google e2 instances

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#243]
Google recently announced that they were going to offer new "E2" compute nodes. These should be theoretically cheaper (the article says by about 30%) without changing performance too much. Worth checking out?

https://techcrunch.com/2019/12/11/google-cloud-gets-a-new-family-of-cheaper-general-purpose-compute-instances/

**Comment by consideRatio** [comment]
Certainly worth considering!

## Relevant notes
1. The E2 machine types does not have sustainable use discount.
2. A e2-highmem-X machine has 8GB of memory/CPU core, while a n1-highmem-X machine has 6.5GB of memory/CPU core, and we bottleneck on memory typically on mybinder.org
3. The price of a n1-highmem-16 is $484.00 / month, while e2-highmem-16 is $527.94 / month in us-central1.
4. Accounting for e2-highmem-16 has 128 GB memory instead of 104 and assuming we only pay for memory, the price can be adjusted from $527.94 to $527.94 * 104 / 128 to compare with the n1-highmem-16, and land at $429.
5. __Conclusion:__ if we ignore CPU performance per core and focus on memory capacity, we get 104 GB memory for $429 using E2 instances and $484 using N1 instances, saving 11.4% but potentially missing out on sustained use discounts for the n1-machines.
6. __Recommended action point to follow this up:__ we evaluate how much sustained use discount we get from various node pools, if we conclude we have more than about 11.4% sustained use discount it could be of relevance to consider.

## References
- [Machine type pricing](https://cloud.google.com/compute/vm-instance-pricing)
  - [n1-machines](https://cloud.google.com/compute/vm-instance-pricing#n1_predefined)
  - [e2-machines](https://cloud.google.com/compute/vm-instance-pricing#e2_predefined)
  - [Sustained use](https://cloud.google.com/compute/vm-instance-pricing#sustained_use)

**Comment by betatim** [comment]
Another limit to consider is that we can only put 100 (or is it 128?) pods on a node. This limit is configurable in "vanilla kubernetes" but on GKE we can't change it. For nodes with a lot of memory we run into this limit first, before we use up all the RAM. This means that the cost per GB needs to be calculated a bit differently to take into account that there will be RAM we pay for but can't use.

**Comment by consideRatio** [comment]
Ive configured the number of nodes on the cluster and pods per node actually, but it relates to networking and IP allocations, something we can only do at the clusters creation on GKE I think. Doing this is a somewhat new feature. Default on GKE is 110 pods, but that means about 100 users as we have some other pods as well.

**Comment by yuvipanda** [comment]
Where did we land on this? At Berkeley, I tried it out and [decided it was not worth it](https://github.com/berkeley-dsep-infra/datahub/issues/1354#issuecomment-614017953). But maybe it is worth it here depending on different usage patterns? In particular, I think it would be useful for things that autoscale heavily.

**Comment by minrk** [comment]
Haven't done the math in a while, but based on the above points, it seems like the sustained use discount on n1 would make it not worth doing. The ceiling for the benefit appears to be very low, at least.

**Comment by yuvipanda** [comment]
I agree! @consideRatio's model is borne out by my small (and not very scientific) experiment, so I think this isn't useful for our use cases. Moving the core nodes might give us a *small* improvement when combined with a committed use discount, but not worth the complexity. I don't plan on renewing our committed use buy at Berkeley.
