### ISSUE TITLE
MIT use of Binder starting 4/1/2020

### ISSUE THREAD

**Issue by shvonski** [jupyterhub/team-compass#275]
Hi All,

As we discussed a few months ago, MIT will be using Binder to host Jupyter notebooks in our course 8.03x.

course: https://courses.edx.org/courses/course-v1:MITx+8.03x+1T2020/course/
repo: https://mybinder.org/v2/gh/mitx-803/vis/master

The first use case will be released to learners tomorrow, 4/1/2020. All use cases are "low stakes" exercises in the course, which are ungraded.

With that said, I believe we have upwards of 1K learners, so I will be curious to know how many are using these notebooks. We had previously discussed the "cap" on users, and maybe extending this to 200 for this repo. Is this possible?

I will be interested to keep our dialogue open and see how this goes! Thanks!

-Alex

**Comment by choldgraf** [comment]
sounds great! If you are curious to see what your activity logs look like, you can see real-time updates here: https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&refresh=1m

and the daily binder launch archive is published here:  https://archive.analytics.mybinder.org/

**Comment by shvonski** [comment]
Thanks! That will be very useful.

**Comment by betatim** [comment]
Do you know if learners have already started looking at this? I had a quick scan of the logs/grafana and was expecting something to obviously stick out like a sore thumb.

**Comment by shvonski** [comment]
Hmm, perhaps not. We release one week of material at a time, and learners
go through it at their own pace. Maybe no one has reached that component
yet?

We have some learners who are very attentive to detail, so I'm sure I will
get a comment from them when they start working on that part.

**Comment by shvonski** [comment]
Is there a way to search for the activity of just ONE repo on the dashboard?

**Comment by choldgraf** [comment]
mmm, not in a super easy fashion. In that case I would probably parse the analytics archive. e.g. you can download the launches for one day with:

```python
import pandas as pd
url = "https://archive.analytics.mybinder.org/events-2020-04-03.jsonl"
pd.read_json(url, lines=True)
```

And then do your filters etc that way

**Comment by shvonski** [comment]
Thanks! I will probably just do this as part of our post-analysis of the course. BTW, we have had some positive comments from users and no issues so far. Thanks for this resource!

**Comment by choldgraf** [comment]
yahoo! 🎉

**Comment by betatim** [comment]
For really up to date usage data Chris' suggestion is the way to go. There is also https://binderlytics.herokuapp.com/binder-launches/binder where you can type the repo name into the search field at the top (https://binderlytics.herokuapp.com/binder-launches/binder?_search=mitx-803&_sort=rowid) for a quick overview. Depends a bit on your SQL skills to make it meaningful beyond "yeah people are using this". (The data available on that website lags behind our archive because updating it hasn't been automated (yet). So it relies on my doing it manually).

There is also https://notebooks.gesis.org/gallery/ which is updated automatically and has a search https://notebooks.gesis.org/gallery/mybinder/7d/ :)

Glad you and the learners like it. Also good to learn that even very large courses don't (yet) lead to huge spikes in traffic. This is good news as it means more big courses could use mybinder.org. Though, let's wait and see how things go when the course is in full swing/a submission deadlines comes/etc.

**Comment by yuvipanda** [comment]
Hey @shvonski! How did this go?

**Comment by shvonski** [comment]
Hi!

This went extremely well. We had great feedback on the interactive widgets
that we created, and students could easily use them through binderhub. Some
downloaded the repo and used them locally.

We are running this course again now. This time our on-campus class (~60
students) will use the repo, in addition to our online course that starts
March 24th.

**Comment by choldgraf** [comment]
wohoo! thanks for the feedback :-) I'm gonna close this issue since I think there's nothing left to do here!
