### ISSUE TITLE
Possibility to bump resources allocated to a repo for a demo?

### ISSUE THREAD

**Issue by FredDeCeuster** [jupyterhub/team-compass#292]
Hi all,

I am Frederik De Ceuster, an astrophysics PhD student at University College London. I am developing a 3D radiative transfer library, called Magritte, to compute the radiative properties and make synthetic observations of astrophysical simulations.

I have the opportunity to give a demo/tutorial of the code at [IAUS366](https://iaus366.be/) on Wednesday October 7th, 2020. (I have not yet received a time slot.) It's a symposium with a participation fee, but speakers are not paid. They expect about 20 to 30 participants for this demo/tutorial. Since it can be tricky to get the code running, and since the demo can be done from within a Jupyter notebook, I would like to use Binder for this. Currently, it works great for simple models, but for the more interesting ones it seems like the allocated resources are a bit low. A test example can be found [here](https://github.com/Magritte-code/Examples/tree/master/2020-05-13_Leuven_LeenMeeting).

Would it be possible to bump the allocated resources for a repo for the duration of a demo?

Thanks in advance! Kind regards,
Frederik

Thanks @sgibson91 , for directing me here!

**Comment by sgibson91** [comment]
Hey @FredDeCeuster, can you provide a link to the repo as well please? Thanks!

**Comment by FredDeCeuster** [comment]
Oh sure:
[Here's a link.](https://github.com/Magritte-code/Examples/tree/master/2020-05-13_Leuven_LeenMeeting)
(This is just a test I planned for tomorrow. The actual demo would be just multiple similar notebooks.)

**Comment by sgibson91** [comment]
For the team here are:

1) (Technologically) Can we temporarily bump CPU/RAM for a specific repo, like we do with concurrent users?
2) Should we offer this in the same way?

It might be food-for-thought regarding the questionnaire/application for such requests we discussed at the last team meeting.

**Comment by betatim** [comment]
Sorry for being late/asking more questions. We discussed at the last team meeting that we should create an issue template for these types of requests. I made a first sketch in a forum post but getting overtaken by requests now because it isn't a template yet. Could we use it for this issue as well? (And then tweak it and make it into a template)

---

To help us keep track of these requests could you please mention create an issue and mention:
* who you are,
* a bit of details about the event/course/context,
* if money is changing hands (attendees pay a fee, speaker is getting paid, free, grant funded, etc)
* a link to the repository you are using,
* what type of event it is (a talk, a workshop, lecture course, training session)
* how many people you expect to attend the event,
* the exact times and dates of the event(s) (with timezone information)

That would be great as it gives us all the information we need to make a decision and set things up. It also allows us to track our impact which will be useful when we report to those who fund mybinder.org or seek new funding.

---

Ideally we edit the first post in this issue to answer the questions. Some of the answers are already in later comments here.

**Comment by betatim** [comment]
I think we have the ability to increase the resources, but we've never used that functionality.

Compared to increasing the concurrent user limit increasing the CPU/RAM limits temporarily means we will be left with repos that during demo times work on mybinder.org but otherwise don't. Repos with increased user limit will always work, even when we remove the special casing again. What do you think about requiring that a repo has examples/code/useful stuff in it that works with the normal limits but we will bump up the CPU/RAM for a limited amount of time to allow people to show off more fancy things?

**Comment by FredDeCeuster** [comment]
Sounds good to me!
I was already planning on also providing "lighter" examples that would always work and have a separate conference repo with the fancy examples.

(I've edited the first post to include the answers to your questions.)

**Comment by arnim** [comment]
mybinder.org is the canonical and stable service to launch binders.

Yet, we have from time to time the same issue of requiring more resources, e.g. for NLP tasks.
https://notebooks.gesis.org is a more experimental deployment that allows for up to 8G mem in anonymous use and up to 32G for authenticated users. 

Here are the launch links for your repository:
+ For anonymous use 
https://notebooks.gesis.org/binder/v2/gh/Magritte-code/Examples/master?urlpath=lab/tree/2020-05-13_Leuven_LeenMeeting/overview.ipynb
+ For authenticated use
https://notebooks.gesis.org/services/binder/v2/gh/Magritte-code/Examples/master?urlpath=lab/tree/2020-05-13_Leuven_LeenMeeting/overview.ipynb

In addition, authenticated use also supports persistence, that is users can come back and continue their work where they have left. 

However, even if you consider using this deployment I would agree with @betatim that including an example in your repository that works with regular mybinder.org resource limits would probably be good.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/sharing-information-when-i-get-8gb-of-memory/4770/1

**Comment by choldgraf** [comment]
closing this as I think it's no longer actionable!
