### ISSUE TITLE
Add a "skills that are helpful to know" section to the contributing docs

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#296]
I was speaking with @hamelsmu recently, who brought up a good point that many people may wish to contribute to the Jupyter(Hub/Lab/etc) communities, and they are interested and willing to learn new skills to do so, but it is unclear exactly _which_ skills would be useful to learn, and how.

For newcomers, the space of infra / dev-ops / etc is *gigantic* and often a bit intimidating (e.g., how deep do you need to go into Docker to be able to work on JupyterHub? What about Kubernetes? What about things like docker-compose or terraform?)

So I wonder if we could put together a short guide along the lines of "so you'd like to contribute to JupyterHub and you don't have background in infra, but you want to learn, here's where to start". What do folks think?

**Comment by yuvipanda** [comment]
The UC Berkeley JupyterHubs docs site has something similar https://docs.datahub.berkeley.edu/en/latest/pre-reqs.html

**Comment by minrk** [comment]
I think that's a great idea. Scoping which things need which skills is important since we have so many different areas of work, which also means there are probably a dozen answers to "here's where to start."

Broad outline of some of the skills/knowledge relevant to different pieces:

- JupyterHub component architecture - Good to know so that you know what there is to work on and what folks are talking about, and what repo might be the place to look at for a given task
- Code architecture of JupyterHub (layout of the repo itself) - Any contributions to the JupyterHub code base <-- this doesn't exist and probably should!
- HTTP and REST APIs - writing services, extensions or maintaining/adding JupyterHub or notebook endpoints, some Authenticators
- Traitlets configuration - Jupyter/JupyterHub configuration <-- this is a big one, often sorely lacking in documentation and probably a really good task to flesh out a primer for
- YAML - z2jh or CI/CD configuration across repos
- k8s basics - z2jh, kubespawner
- Helm, go templating - z2jh
- tornado/asyncio - Working on JupyterHub code or Authenticators/Spawners, etc.
- HTML, CSS, jinja - jupyterhub pages
- Javascript - pretty minimal, but some dynamic JupyterHub page content
- pytest, http mocking - testing
- Docker - updating images for z2jh, dockerspawner, etc.

I'm sure there are more. Maybe we should write some step-by-step contributor tutorials starting from "I want to do X" where we go through logical steps for a contributor to take and what skills are needed at each step? Some example tasks:

- Fix a bug in a Spawner
  - find the relevant code
  - reproduce the bug and write a regression test
  - run the tests
  - debug and fix it
- Change some CSS on jupyterhub page X
  - find relevant LESS (also: wtf is LESS)
  - edit LESS
  - build CSS
  - launch developer jupyterhub to test pages
- Add support for a new Authenticator in z2jh
  - Add package to hub requirements.txt
  - add config option(s) to values.yaml
  - Add docs
  - Test??? (chartpress? minikube?)


Depth/expertise required for certain kinds of tasks is pretty hard to nail down and not at all obvious. Updating/adding a package in our hub image isn't too complicated (you still need to find where that lives). Adding a simple configuration option to z2jh might seem simple, but is actually pretty complicated (much less so now than it used to be) because we are tying together two or more systems of configuration (helm yaml config -> helm template into kube data structure -> jupyterhub traitlets config).


One thing that I've found to be not a super productive place to start is "I want to contribute" since there are so many things that can mean to different folks. Having your own challenges to solve tends to be the most effective way to get started, and provides a smoother transition to helping solve other people's problems. Still, bug reproduction and issue triage/clarification is one of the absolute most useful general tasks we are perpetually short on resources for. If folks want to be open source super heroes, turning open bug reports into failing tests is one of the most useful, productive, often time-consuming things one can do. Similarly, turning "How do I...?" questions into improved documentation is among the most valuable contributions a person can make. One pattern I find really rewarding (but still usually fail to do) is when someone asks a question that I know the answer to, try to point them to an answer in the documentation. If there isn't one, *write the answer as new/improved docs* and then point the question to a docs PR.

**Comment by betatim** [comment]
I like the idea! I also really like the idea of "no docs? let me make some and then point the user there". I will try and adopt that strategy (kinda like "write a test for bug reports so the bug doesn't come back").

Two more area - skill pairs:

* technical writing - documentation: structure, content, clarity
* user experience - UI elements, structure/flow of interactions, accessibility 

In the repo2docker issue template for new features there is a section on "who can do this work" https://raw.githubusercontent.com/jupyter/repo2docker/master/.github/ISSUE_TEMPLATE/feature_request.md which asks for "what skills do people need?". Sometimes this has worked and sometimes people misunderstand it and write something like "anyone". Despite this I find it helpful as anything people add makes it easier to expand/edit it than writing it completely from scratch. If we had some canned links for the common areas of skills required that would be a cool resource to have to flesh out that section per issue.

**Comment by consideRatio** [comment]
Posting some relevant content to reference regarding docker / k8s / helm.

### What is Kubernetes / Helm

Kubernetes is an open source system allowing you to declare _docker containers_ you want to have running along with required networking and storage requirements they have. While doing this, you may end up with many _Kubernetes resource files_, and this is when Helm can help you _package_ them into one unit. A Helm package which is also called a _Helm chart_, can be customized and installed/upgraded more easily than if you had a collection of Kubernetes resource files.

### Learning resources

##### [Video: What is Kubernetes?](https://www.youtube.com/watch?v=VnvRFRk_51k)

##### [Playlist: Intro to Docker, Kubernetes, Helm, etc](https://www.youtube.com/playlist?list=PLy7NrYWoggjwPggqtFsI_zMAwvG0SqYCb)

##### [Video: Kubernetes deconstructed](https://vimeo.com/245778144/4d1d597c5e)

##### [Video: What is Helm](https://www.youtube.com/watch?v=-ykwb1d0DXU)

### Tooling advice

After having installed the common tools [docker](https://docs.docker.com/get-docker/), [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/), and [helm](https://helm.sh/docs/intro/install/), , also _make sure to setup_ [kubectl tab completion](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion) and [helm tab completion](https://helm.sh/docs/helm/helm_completion/) as well! If you would like a GUI working against your Kubernetes cluster, https://github.com/lensapp/lens seems to be the most promising at the moment.

**Comment by choldgraf** [comment]
OK, I took a pass at trying to collect the information above and turn it into a
first-pass PR to add this to our documentation, here:

https://github.com/jupyterhub/team-compass/pull/301

In addition, there were a few points above that I think are actionable in other
repositories, so I've created issues to track each one:

Traitlets primer: https://github.com/jupyterhub/team-compass/issues/300
JupyterHub repo architecture: https://github.com/jupyterhub/jupyterhub/issues/3080
K8S primer: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1693

Would love to know what folks think and iterate on this a bit!

**Comment by choldgraf** [comment]
I'm gonna close this since we've got #301 merged-in, and have issues for the other points we discussed. Thanks so much everybody for your help :-)

**Comment by hamelsmu** [comment]
Thanks for adding this.  This information is very useful.  Gives someone like me a better starting point on what to learn and how to focus my efforts to become a contributor.  Really appreciate it.
