### ISSUE TITLE
Docker hub storage time limits

### ISSUE THREAD

**Issue by manics** [jupyterhub/team-compass#330]
Received this today: Docker Hub images not pulled or pushed in the last 6 months will be deleted, starting from 1 Nov 2020
https://www.docker.com/pricing/retentionfaq

> What is a container image retention limit and how does it affect my account?
>
> Image retention is based on the activity of each individual image stored within a user account. If an image has not either been pulled or pushed in the amount of time specified in your subscription plan, the image will be tagged “inactive.” Any images that are tagged as “inactive” will be scheduled for deletion. Only accounts that are on the Free individual or organization plans will be subject to image retention limits. A new dashboard will also be available in Docker Hub that offers the ability to view the status of all of your container images.

> What are the new container image retention limits?
>
> Docker is introducing a container image retention policy which will be enforced starting November 1, 2020. The container image retention policy will apply to the following plans:
>    Free plans will have a 6 month image retention limit
>    Pro and Team plans will have unlimited image retention

**Comment by betatim** [comment]
I added it to the agenda for next weeks team meeting.

**Comment by minrk** [comment]
*Jotting down some notes ahead of the meeting*

To me, the big question is: **Do we want a long-term archive of images not actively in use; if so, which ones?**

The main thing of ours that I think might be affected are published releases of images like those in the helm charts. The practical result of this that I see is that if nobody installs a version of the chart, jupyterhub, etc. in 6 months, that release will become broken (helm) or unavailable (docker images). It's not the hugest deal, since nobody pulling a given version in 6 months makes it pretty unlikely that someone will do so in the future (I guess that's why they are doing this). If we decide we want to take some mitigating action, we could do one (or more) of:

1. nothing, let the reaper come and wait for possible problems
2. create a paid docker account so nothing gets deleted
3. cheat a bit to keep versioned releases alive by doing explicit periodic pulls of releases (I think expiring our intermediate dev releases is a *good* thing, so we shouldn't do anything for those)
4. move our images to [quay](https://quay.io) which appears to still have unlimited storage for open source projects (or another host)
5. garbage collect our development-versions of the helm charts so we don't keep every intermediate version of every chart forever, which we are doing now. This would address the coming mismatch between the helm chart repository which never deletes things and the image repository where inactive versions will be deleted

**Comment by yuvipanda** [comment]
At least for z2jh, I'd love for us to keep all the images alive. If someone had set up a hub on a version that wasn't released (many people did, esp. during the time https was broken in released version), it will fail in weird ways - particularly, when the hub / proxy pods try to get scheduled in a new node. That's no fun. Similar for images in jupyter/docker-stacks - even more so for those, since there isn't really 'releases' there.

**Comment by minrk** [comment]
Yeah, that would be ideal, if feasible.

While it's technically possible, I don't know how likely it is that an active deployment will go 6 months between pulls of an image. A small fixed-size cluster could do this, I suppose. If we set the default imagePullPolicy to Always, it would also set the timer at the last pod restart, which would be *extremely* unlikely to expire after 6 months of an active deployment.

In general, I'm not sure we should commit to supporting dev versions for more than six months (related to this: we should make sure we are making 'stable' releases more often than that!). Running on a dev version when you need a fix not yet released is one thing, but staying on an dev version for a long time after there's been a release since then is not very feasible from a support standpoint. docker-stacks doesn't have a 'stable release' pattern to fall back on, but single-user images seem like they would be pulled *even more often* than e.g. the Hub image, so would have a harder time being marked 'inactive' when actually in use.

It would be interesting to see how many images are deployed in the wild that will be marked as 'inactive', but I'm not sure we can collect that. My guess would be 0 or close to it, but I could be wrong.

**Comment by manics** [comment]
https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/
The 6 month image retention policy has been delayed, but docker pull limits will be enforced.

**Comment by betatim** [comment]
Some more thought on the different ways the limit effects mybinder.org https://discourse.jupyter.org/t/dockerhub-pull-limits-mybinder-org/6381/2?u=betatim

**Comment by choldgraf** [comment]
Also just a note that this is probably worth keeping an eye on:

https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/

Looks like AWS is also going to roll out public docker image registry improvements soon, maybe worth utilizing...

**Comment by choldgraf** [comment]
Since we are now generally using quay.io for things, can we close this one?

**Comment by manics** [comment]
Yes, we're still dependent on Docker Hub but quay.io is the future and we can slowly update things 😃
