### ISSUE TITLE
Sustainability in Open Source Projects Study - Participate?

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#417]
My friend @yochannah is running a study into which KPIs are common to open source projects that overcome typical barriers to sustainability (e.g. maintainers move on, funding dries up). More info here: https://sustainable-open-science-and-software.github.io/

Should we (JupyterHub and/or Binder) participate? It involves providing the URL to a repo so that KPIs can be pulled over the GitHub API and filling in a survey when joining the study and at 6 and 12 month intervals.

**Comment by manics** [comment]
Sounds fine to me! Would they monitor one repo or several, or the GitHub org as a whole? There are definitely differences between a high profile repo like JupyterHub and repos like OAuthenticator or LDAPauthentictor which are active but lacking in people with deep understanding.

**Comment by sgibson91** [comment]
That might be something to discuss with Yo. I suspect the study has been setup for single repo projects. An org as large as JupyterHub might be overwhelming to do all the checks on (some of which are manual), but we could maybe select ~3 that cover the scope of activity we see?

**Comment by yochannah** [comment]
Three would be great - thanks @sgibson91 ! 💜

**Comment by yochannah** [comment]
@sgibson91 just FYI - I'm planning to close this survey on the 10th! :)

**Comment by sgibson91** [comment]
Good to know, thanks!

@manics do you reckon you could come up with 3 repos that would capture the scope of activity across JupyterHub? I'm happy to fill in the surveys.

**Comment by minrk** [comment]
My initial thought would be the best summary would come from: jupyterhub, zero-to-jupyterhub, and binderhub

Other likely candidates:

- repo2docker
- kubespawner
- mybinder.org-deploy (very different workflow / community. Might be interesting, might also be noisy.)

or oauthenticator/ldapauthenticator/dockerspawner as @manics mentioned if we want to capture a *variety* of repos

**Comment by manics** [comment]
My thoughts were to go for a variety of repos, but we probably need @yochannah's input on what's useful. @minrk's suggestion sound good if we want to focus on the main repos, otherwise what do you think of:
1. One of the "flagship" repos, most likely Jupyterhub since it's what the org is named after!
2. One of the backend repos like an authenticator or spawner. In the absence of any other preference how about ldapauthenticator?
3. Either a utility repo like nbgitpuller or jupyter-server-proxy, or repo2docker. I'm leaning towards repo2docker since it has a different development process- it's also about defining a specification as well as an implementation.

**Comment by yochannah** [comment]
thanks folks - I'll second that a variety would be great. If hopping up to
four or five is better, that's fine too.

**Comment by minrk** [comment]
If we want variety, I'd say:

- jupyterhub (core functionality, more developer-focused)
- zero-to-jupyterhub (most active, I think, more user-focused)
- ldapauthenticator
- repo2docker
- (if we want one more) mybinder.org-deploy, which is a very different kind of repo!

**Comment by sgibson91** [comment]
Cool, I submitted using @minrk's suggestions for repos!
