### ISSUE TITLE
Refreshing council membership

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#566]
Dear JupyterHub team members!

As part of the larger Jupyter governance reorganization, we are updating the JupyterHub team structure and membership.
We haven't checked in on continuing active membership as we had originally decided to do, so we are checking in now.
Please comment on this issue with your preferred status (for more information on each role, [see here](https://jupyterhub-team-compass.readthedocs.io/en/latest/team/index.html)) (or you can send me an email if you prefer):

- Council member
- Maintainer
- Team member
- Inactive member

If we don't receive a response by <del>Tuesday, September 27</del>Thursday, September 29, we will list you as an __Inactive member__. You are always welcome to re-join an active team.

Current team members:

- [x] @carreau
- [x] @GeorgianaElena
- [ ] @jzf2101
- [x] @sgibson91
- [x] @betatim
- [x] @choldgraf
- [x] @manics
- [ ] @mpacer
- [x] @yuvipanda
- [x] @minrk
- [x] @consideRatio
- [x] @willingc
- [x] @lheagy
- [x] @Zsailer

I'll send an email on Friday to prompt anyone who hasn't responded by then.

**Comment by minrk** [comment]
Council member for me!

More information can be found in #497

**Comment by Zsailer** [comment]
Thanks, Min! 

I'm going to remain inactive at this time, but I'm proud of this team and all the great work y'all are doing! ❤️

**Comment by sgibson91** [comment]
Council member please :)

If you need a refresher on what the roles are: https://jupyterhub-team-compass.readthedocs.io/en/latest/team/structure.html

**Comment by lheagy** [comment]
Thanks Min! 

I will be remaining inactive too. But still excited about all of the work by this amazing team 🚀

**Comment by manics** [comment]
Either maintainer or council member.... not sure.

**Comment by betatim** [comment]
Council member please.

**Comment by consideRatio** [comment]
Like Simon I'd like to either be maintainer or council member. At the moment and not being confident on what makes sense, but I'm leaning towards a __council member__ to gain such experience.

**Comment by GeorgianaElena** [comment]
I feel the same way as Erik and Simon about maintainer vs. council member, with a preference towards being a council member and gaining experience as I go.

**Comment by yuvipanda** [comment]
I’ll take council member too!

**Comment by choldgraf** [comment]
Hey all - I'd like to be a member of the Steering Council, but I want to recognize that I'm concerned I will not be able strictly adhere to the responsibilities of being a steering council member. I likely will not be able to make (m)any of the team meeting times because they coincide with when I am spending time with my family. I will do my best to read these meeting notes asynchronously and provide feedback at a high level, but I likely will not attend.

In my opinion, it is crucial that steering council members embody the responsibilities and expectations of membership, and I don't want to dilute the value of the role by being involved just because I have been around for a long time and people know who I am. On the other hand, I think there are still ways that I can be helpful at a high level around team process, docs, strategy, fundraising, etc.

I am legitimately conflicted on this, so I welcome anybody to reach out publicly or privately to discuss this with me. Right now I am leaning towards requesting council membership and then seeing how I feel about it in a year.

**Comment by willingc** [comment]
I feel similarly as @choldgraf. For now, I request council membership and will reevaluate my time commitment in a year.

**Comment by minrk** [comment]
Those are excellent points, and I think it's worth exploring the details of the expectations for meetings. It's literally impossible to schedule regular meetings that work for everyone on the globe, and our expectations must reflect that (our scheduling should also reflect expectations being reasonably satisfied).

In my mind, the dual time zone pattern we have means that nobody should be _expected_ to attend more than one time zone meeting. But that's also only one meeting every two months, so missing one for random conflicts becomes a bigger deal.

I think it's appropriate for the SC _as a whole_ to be responsible for ensuring sufficient attendance (e.g. via setting the schedule), and for individuals to be responsible for paying attention via notes, etc.

The overall Jupyter SC never had any standing meetings, and I don't think we need to connect the SC directly to meetings for JupyterHub.

**Comment by Carreau** [comment]
Hi All, 

I think you can move me to inactive member, I only contribute rarely. My only needs on these repos is to open security advisories when reports are made.
