### ISSUE TITLE
Add branch protection for main branches?

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#595]
GitHub's decided to get pretty annoying about bugging us to add branch protection rules everywhere, putting banners like this on every repo:

<img width="1059" alt="Screenshot 2022-11-28 at 13 22 49" src="https://user-images.githubusercontent.com/151929/204277105-c3d9698f-3089-407e-8ed9-03f9cf4eff33.png">

I don't actually think we should add any of the opt-in branch protection rules like require CI pass or review before merge because I'd rather trust maintainers on those points (though #594 may suggest adding review before merge?). But creating an empty branch protection rule with no boxes checked does have value, because it prevents force-push and branch deletion, which I think are both good and uncontroversial. The biggest reason to add rules like requiring CI checks is that it enables automerge, so you can say "merge this PR once the CI passes", which is nice when the tests take a long time! Doesn't matter much, otherwise.

If folks agree, I can probably script bulk-creation of those default rules to get rid of the complaining banners. I've made one or two by hand out of sheer annoyance.

**Comment by choldgraf** [comment]
I think at a minimum, we should start by adding branch protection for:

- no force push
- no branch delete

and discuss if we want something more strict beyond that.

For more strict stuff, I think that "require tests to be passing" is reasonable, with the knowledge that anybody with `admin` access can also bypass these rules and merge anyway if there's a clear reason to do so. I think anybody on the steering council should have `admin` privileges across all jupyterhub repositories, and a repository's admins can agree to give admin privileges to a maintainer on a repo-by-repo basis. That way it's still possible but feels a little bit more "intentional". But I don't feel strongly about this.

Finally, I think we might consider having these slightly stronger branch protection rules only for a subset of repositories that are more heavily used.

**Comment by betatim** [comment]
I'm in favour of the uncontroversial benefits of branch protection (no force push, branch delete).

For the other things I prefer to keep things as guidelines instead of rules (enforced by bots). There are times when you want to make an exception or don't want something auto-merged despite CI being green and having enough positive reviews. They trigger my "technical solutions to social problems" knee jerk reaction. And it doesn't seem we have any of the social problems that these branch protection rules would save us from, I think it isn't worth activating them.

Auto-merge seems like something that could be nice, but I do wonder if this is fixing a symptom instead of treating the underlying cause. My guess is that "Tests are never ready in time so I need to come back" is the symptom, and the underlying cause is maybe slow tests, flaky tests, too many tests, not enough test runner slots, etc. We can address all of those and it would be a net gain for everyone, not just those waiting for the merge button to turn green. Of course it is also more work :-/

**Comment by betatim** [comment]
There was a discussion around "auto merge" in the scikit-learn repo. I learnt that once enabled a human has to activate it on a per PR basis and that there is a "override this" option (in case the branch protection rules aren't met). After learning these two things I am now in favour of activating auto-merge on repos and seeing what happens.

(Still think making the CI run faster is a good thing though.)

**Comment by manics** [comment]
Yes, go ahead with the basic rules, and let's discuss the more advanced stuff like auto-merge or enforcing passing CI for non-admins separately.

**Comment by minrk** [comment]
Yeah, I was just going to add the very basic ones. We can still discuss the more advanced stuff and maybe do a trial on a repo or two.

**Comment by minrk** [comment]
I added branch protection rules to all our repos. Only took 2 http requests with graphQL! https://nbviewer.org/gist/6ffacd5a993e4fc6769e5e3a0a039780

**Comment by consideRatio** [comment]
Nice @minrk!! Then I figure we can close this issue, and another can be opened for further discussion about auto-merge stuff.
