### ISSUE TITLE
Everybody vote in the Jupyter Executive Council election

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#597]
The Jupyter Project is currently electing its first [Executive Council](https://jupyter.org/governance/executive_council.html). This is a group that leads the organization as a whole and stewards its mission and operations.

**I believe any [JupyterHub Council](https://jupyterhub-team-compass.readthedocs.io/en/latest/team/index.html) member may vote before December 4th**.

- [The election guide and self-nomination forms are here](https://drive.google.com/file/d/1im6rueLUrZl5ICWqz3PLIm91dTC3M2AE/view?usp=sharing)
- [A voting ballot is here](https://forms.gle/89JQTk7nFiSehiv2A)
- [A Discourse thread to ask questions](https://discourse.jupyter.org/t/jupyter-executive-council-2022-election/16840)

**Comment by betatim** [comment]
Thanks for posting this. I hadn't realise there was an election, that nominations had already been collected and that only a few days are left to cast a vote. All a bit jarring given the otherwise more sedate pace of the Jupyter governance refactor.

Do you know where I could have subscribed myself to have learnt about this in good time?

**Comment by minrk** [comment]
Our lack of a team contact point (#598) is a big part of this. The process started over a month ago, and some JupyterHub members were contacted individually by the governance team, but I missed who was not included. If our council had a contact point, that's where that notice would have gone. I should have forwarded the email when I got it to the remaining members (the mail even explicitly asked me to do just that), but failed to do so.

There's more info [in the governance docs](https://jupyter.org/governance/executive_council.html#council-membership-and-elections). All members of any team council can vote, so that includes everyone listed as "JupyterHub council" [here](https://jupyterhub-team-compass.readthedocs.io/en/latest/team/index.html).

**Comment by betatim** [comment]
No worries. Lets fix up the email address for the team so that can be used in the future.

**Comment by choldgraf** [comment]
I believe that this election is now complete, so I'll close this one.
