### ISSUE TITLE
Create a mailing list for the JupyterHub Council and Team

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#598]
We recently had a communication from @fperez regarding voting for the Jupyter Executive Council election. He wanted to send a message with information to the JupyterHub Council, but did not find a public way to quickly communicate with this group. We need a way for others to quickly get in touch with the whole group if there is important information to convey.

Moreover, there may be times where it's important to have non-public discussion amongst the JupyterHub Council. Right now we have no official place to do this.

### Proposal

I propose that we take the following actions:

- Create a `jupyterhub-steering-council` Google Group and use this as an official space for **private** team communication, and the one way to "get in touch with the whole jupyterhub team at once".
- Ensure that any council member is added to this group.
- Document our use of `mybinderteam@googlegroups.com` in the team compass

### Alternatives

Alternatively we could use a GitHub team (like `@jupyterhub/steering-council`). I think this would be "cleaner" and easier to remember, but I'm not sure how accessible it would be for communication.

### Checkpoints

- [x] Create a Google Group for `jupyterhub-team-council@googlegroups.com`: https://groups.google.com/u/1/g/jupyterhub-team-council/members
- [ ] Document our practice in the team compass

**Comment by minrk** [comment]
GitHub teams sounds really nice, but I don't think there's a way to contact a team privately, is there? That would suggest the ML is the way to go. I'd _like_ to have both (e.g. for vote pings, requests for review), but I also don't like too many communication channels for the same thing.

**Comment by manics** [comment]
You can have private GitHub teams discussions, for example
https://github.com/orgs/jupyterhub/teams/jupyterhubteam

**Comment by minrk** [comment]
Right. But one important aspect is for folks _not_ on the team to be able to start the conversation. Is that possible with teams?

**Comment by betatim** [comment]
I think an email address that forwards to all involved (e.g. a google groups thing) would be the easiest for the cases where external people want to get in touch. Mostly because email is something everyone can do. Maybe it isn't the nicest solution, but then we seem to not need it very often. So a low effort solution is nice.

Slightly off-topic, why can people not create an issue here? Even if all they say is "is there a way to get hold of you privately please?" Especially for something as important as the council elections which are the outcome of a multi year process (getting it right is more important than speed).

**Comment by minrk** [comment]
> why can people not create an issue here?

I think they absolutely can. The question then becomes, how do they know that's how we want them to contact us? We need a contact section in our team docs that suggests people do that, otherwise we're going to get all kinds of different contacts with no real expectation that folks do otherwise. Whether that's an email, this repo, etc. matters less than whatever it is being clearly stated and discoverable.

**Comment by manics** [comment]
First we need to decide what the purpose of this list is. Is it so that the Jupyter Executive have a single point of contact with JupyterHub, or is it the more general problem of a single public point of contact open to anyone?

For the former (Jupyter Executive) I think adding them to the same GitHub team, and having a document on the Jupyter Executive side that indicates how each of the subprojects should be communicated with, could work?

For the latter case.... email is probably only option that works for everyone despite its flaws, with documentation on the JupyterHub and Executive sides.

**Comment by minrk** [comment]
I think it's a general issue, though use from external contacts is probably pretty rare. I think a mailing list makes sense as the least common denominator for communication with a group.

**Comment by choldgraf** [comment]
Why don't we add a section like this:

```
## How to get in touch with the JupyterHub Council

There are two recommended ways to send communications to the JupyterHub council:

1. **Open an issue in our [Team Compass](https://jupyterhub-team-compass.readthedocs.io)**. We use this as a space for team discussion of all kinds, and JupyterHub Council members are expected to monitor these issues.
2. **Send an e-mail to [`jupyterhub-team-council@googlegroups.com`](mailto:jupyterhub-team-council@googlegroups.com)**. This is a shared inbox that we use for people that prefer non-public or e-mail communication instead of GitHub issues.
```

**Comment by manics** [comment]
@choldgraf that sounds fine to me. Do you think we should emphasize (1) as the preferred channel on the grounds of promoting open-discussion?

**Comment by choldgraf** [comment]
OK, I've done these things:

- **Created a JupyterHub Team Council google group**. [Here's a link](https://groups.google.com/u/1/g/jupyterhub-team-council/members).
- Add everybody listed in the [JupyterHub team page](https://jupyterhub-team-compass.readthedocs.io/en/latest/team/index.html)
- I used the e-mail I had on file for you, but I **also made everybody an owner of this group**, so please add a different e-mail and remove your old e-mail if you wish.
- **Created a PR** to document these practices: https://github.com/jupyterhub/team-compass/pull/599
