### ISSUE TITLE
Split and refactor the team meeting format (1/2): Collaboration Café

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#617]
## Context

From regularly leading the monthly team meetings, I have come to the conclusion that they are not a very welcoming or consistent entry point for newcomers to JupyterHub, even though the meeting is "open to everyone". This is because the agenda varies wildly depending on what the community wants to discuss, which is amazing that it is emergent, but not consistent.

I think it's quite off-putting for people who are not yet familiar with the project to attend these meetings when they become very technical, or very strategy/governance heavy, for example, and I've often seen that new folk only come to one meeting and likely never return. I think this is also because the meeting doesn't help orient newcomers to the project or where they can begin to help, even though we invite them to the meeting to do precisely that!

## Proposal

I propose that breaking up and refactoring the meeting will be more beneficial to newcomers who want to gain a clearer sense of the project and where to begin contributing, without being drowned by complex technical challenges or governance strategies straight off the bat.

I propose two types of meeting: a Steering Council meeting (to be tracked in another issue, TBA), and something akin to the _Turing Way's_ Collaboration Café[^1].

[^1]: https://the-turing-way.netlify.app/community-handbook/coworking/coworking-collabcafe.html

### What is a Collaboration Café?

The Turing Way's Collaboration Café is a two hour block of time every 1st and 3rd Wednesday of the month where members of the community make time to work on the Turing Way, either as a time block for their own work they'd like to do or to collaborate with other community members in real time. This is structured as many break-out rooms covering topics, that could include:

- Quiet working
- A group of people who want to discuss a specific topic, such as issue triaging or writing a new chapter
- Onboarding. Newcomers are directed to the Collaboration Café as an initial touchpoint where an experienced member of the community describes the project and its purpose, how the community works together, and how they can start contributing.

The breakout rooms work in pomodoro[^2] sessions with breaks back in the main room to share progress across the groups.

[^2]: https://en.wikipedia.org/wiki/Pomodoro_Technique

Hosting a Collaboration Café-like event may reap dual benefits of being more friendly to newcomers, and keeping the emergent nature of "what does the community want to talk about this session?" that the current team meeting has - including really technical stuff! Attendees can choose which conversation to participate in based on their needs. This will also give folk a space where they can start coordinating and actioning their ideas since it is a more collaborative space than a meeting.

### What would a Collaboration Café-like session require?

- **Someone to chair.** This person would be in charge of breakout rooms, getting people where they need to be, timing the pomodoros, and would remain in the main room in case someone joined the call while everyone was in breakout rooms.
- **Really good running notes!** In order to ensure sharing of information when folks are in breakout rooms, We will need high quality shared notes alongside the share-outs between pomodoro sessions. See the Turing Way's shared notes for an example: https://hackmd.io/@turingway/collaboration-cafe
- **Really clear communications.**
  - Folk don't like uncertainty around what they are showing up to. So in order for newcomers to feel confident in attending, we should communicate that a breakout room for onboarding will _always_ be available for every call. (We don't actually have to open it if no one shows up to be onboarded 😉 )
  - We should make it clear that this is a virtual, co-working-like event. I don't think this will be too problematic for our community that has always been remote, but there were a few "I'll come next time I'm in London!" responses when Collaboration Cafés first started in the Turing Way 😂 (pre-pandemic)

## Actions

- [ ] Consensus from the team that this is worth piloting
- [ ] When should this call happen, how frequently, and for how long? (We should try to keep alternating time zones too)
- [ ] How to communicate this change to the community? Blog, Discourse post, anything else?

**Comment by betatim** [comment]
A 👍  from me after my recent experience of joining the scikit-learn project. You do feel like you are dropped into the deep end and totally bamboozled by the going ons and discussion topics. It feels like you'd have to attend for several months before you can make a contribution or say something.

I like the idea you propose. An "on ramp" to the meetings of the project.

---

Another idea I had before seeing this (thinking about how to make my life easier in scikit-learn) was to have a fairly "formulaic" first agenda item for each meeting. Maybe like a "State of the project" that reports on things since the last meeting. Formulaic in the sense that the agenda item would always follow the same structure. For example: new contributors who joined since the last meeting, upcoming release date/celebrate last release, stats of issues opened/closed, stats on PRs opened/closed, shout out to blog posts, upcoming conferences.

I got the idea from thinking about how the big collaborations I used to be part of worked. We had quarterly(?) collaboration weeks (basically a conference but only collaboration members attended). As part of these there was always a report from the management (highlights and high level stuffs), a report from the speakers bureau (upcoming conferences, abstracts that had been submitted, stats on who is giving talks), a run report (did we take data? how much? exciting things from operations, new records, etc), etc, etc. On the face of it they seemed a bit boring, but it was nice that each of them touched on roughly the same topics each time. So it gave you some continuity and "ah, I know where I am and what will happen next" compared to the rest of the week which was a total whirlwind of new people, new topics, new setting, etc. 

Maybe interesting to think about, but I think the collab cafe is a more proven idea.

**Comment by sgibson91** [comment]
Thanks Tim! I like your ideas. The Collab Cafe usually starts with an icebreaker of some sort and "what do people want to work on?" So we could include some kind of "status update" during that initial preamble :)

**Comment by GeorgianaElena** [comment]
It has recently come up in another conversation the need and importance of a collaborative triaging effort. I figured this might be a good place to further refine the ideas in that conversations and a place for them to live so we don't loose track of them (cc @minrk @consideRatio )

### Erik's ideas

- _Weekly / bi-weekly repo to triage! I like the idea of picking a repo as it helps us collectively catch up and discuss a related topic (a chosen projects), and offloads jupyterhub maintainers from choosing what to focus on themselves individually. I think this could also help us onboard maintainers to new projects etc._
- _Triage dashboard? It could be nice to have some overview from a dashboard, summarizing issues / PR metrics across jupyterhub repos. This could be used to help guide the choice of what repo to focus on also among other things._
- _Triage hours? There could also be for example two weekly hours or so where this kind of work is encouraged, maybe with an associated gitter channel?_

### Min's feedback

_dashboard’s hard because the main input is “how many are waiting for maintainer action” not “how many total”, and it’s very hard to say that clearly_

_and one of the main activities in triage is going through all items and identifying which those are, because it can’t be really be done automatically_

_‘obvious’ triage includes issues with zero comments, but arguably the most important are the longer conversations that are at risk of going stale awaiting maintainer input_

**Comment by GeorgianaElena** [comment]
My personal proposal, built upon the great feedback from you all:

## A Collaboration Café for improving project maintainability

I would love for us to create a space for collaborating on maintaining the project/s (triaging issues, reviewing PRs, responding to Discourse questions etc).

But I believe it needs to be something that's very low effort and doesn't require a lot of time commitment, at least in the beginning until we make a habit out of it.

### 1. Start with a dedicated "maintainability" Gitter channel 

- have a Gitter channel dedicated for collaborating on maintainer-related chores (triaging issues, reviewing PRs, responding to Discourse questions etc)

The desired outcome is to create **a team of at least two people** dedicated to the same effort

_Note: we can have a video conference link where we can quickly jump to for quick discussions or for quiet working?_

### 2. Invite, engage with, and guide new people in this effort

I believe "improving project maintainability" also means bringing in new maintainer and contributors to help with projects.
So, this channel can also be a place where:

- contributors join to say "hey, I want to help out with maintaining this project, but don't know how/where to start" and then we create a team of existing maintainers to assist with this

### 3. Help us review your work

This step is to help de-mystify the review process, have quicker review and also bring new people in.

- contributors with open PRs that haven't yet received feedback for _x_ amount of time are encouraged (by a bot?) to come to this channel and help maintainers review their work by:
   - providing extra details
   - answer maintainers' questions
   - ask maintainers for extra clarification

### (Optional) Commit to be available on this channel for sync discussion once day a week or bi-weekly?

**Comment by sgibson91** [comment]
> _Note: we can have a video conference link where we can quickly jump to for quick discussions or for quiet working?_

I actually think this could be a regular breakout room inside the Collab Café, the same as the onboarding breakout

So for example, every time we hold a Collab Café, we say there's always a breakout room available for onboarding, and another breakout room always available for maintenance/triaging, and we open as many other breakout rooms as are required depending on what other topics folk want to discuss during the Collab Cafe. So these don't need to be happening in separate spaces and folk can move between breakouts as they might tables in an actual cafe :)

**Comment by sgibson91** [comment]
Another idea that arose in a discussion with @choldgraf is incorporating a lightweight mechanism for "what kinda things to we want to accomplish in the next few months" and "what more specific things do we want to focus on the in the next weeks".

So we could maybe start the collab cafe with a sprint that involves everyone to talk about these issues for a bit, and then subsequent sprints could be people organising and beginning work around one or more of the subtopics brought up in that initial sprint (these may overlap with the maintenance and onboarding rooms - and that's ok!)

**Comment by sgibson91** [comment]
I think I will spend my focussed time from February on setting this collab cafe up

**Comment by minrk** [comment]
I think that sounds great!

**Comment by sgibson91** [comment]
Some things to work on this month:

- Investigate Jitsi's breakout room functionality. We may need to switch platforms if this is not up to par.
- Set a regular time and duration for the collab cafe
- Discuss/announce in Feb team meeting and discourse and/or blog
- Aim for first collab cafe in March

**Comment by sgaist** [comment]
This sounds like a pretty great initiative !

On the organizational side of things, I am guessing that it would be put in a calendar for people to know when it happens. In that case, would it be possible to have a notification set like 10 minutes before the event starts ?

I have missed several of the JupyterHub monthly meetings because although I have subscribed to the Google Calendar so it shows in mine, I was often deep into something and only saw too late that the meeting had happened.

**Comment by sgibson91** [comment]
There is a blog post up explaining what will happen! https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15
