### ISSUE TITLE
Use of codecov's service to overview test coverage - setup by default?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#640]
I've never properly used the code coverage information, and I don't know for sure whats required to set it up either.

- Should we set it up by default in new projects?
- In what way is it used currently? Is it as quick checks of if new code is tested by looking at some specific metric etc?

I'm raising this question here as I can't directly answer @Sheila-nk's question in https://github.com/jupyterhub/pytest-jupyterhub/issues/47

**Comment by consideRatio** [comment]
I figure if we are to set it up, I could investigate how and what needs to be done.

### Investigation on how to setup codecov

@sheila-nk links to [codecov quick-start](https://docs.codecov.com/docs/quick-start) guide, and looking at that I see **6 steps**:

**[Step 1](https://docs.codecov.com/docs/quick-start#step-1-sign-up-for-codecov) mentions signing up / logging in**

Logging in with GitHub as an identity provider, I can see the following for jupyterhub/pytest-jupyterhub for example, it was listed as "not set up".

![image](https://user-images.githubusercontent.com/3837114/232025239-2b7f0874-c526-4f84-995f-7315b3857c2e.png)

**[Step 2](https://docs.codecov.com/docs/quick-start#step-2-get-the-repository-upload-token) is about setting up a CODECOV_TOKEN via "setup repo" button**

This step was _described as optional_ when using with public repositories and GitHub Actions - which we do! Due to that, this should be fine to ignore for us I think. For reference, I wen't ahead and pressed "setup repo" and saw this:

![image](https://user-images.githubusercontent.com/3837114/232025774-59d1eea5-6865-4523-b3c5-d0c4a63202a5.png)

**[Step 3](https://docs.codecov.com/docs/quick-start#step-3-setup-integrationteam-bot) mentions a authorizing the codecov GitHub Application**

The JupyterHub organization [has authorized use](https://github.com/organizations/jupyterhub/settings/installations/266222) of the [codecov github application](https://github.com/apps/codecov) for all repositories.

![image](https://user-images.githubusercontent.com/3837114/232022547-972cf272-3ae4-45ed-bbdc-564cbc00fa71.png)

**[Step 4](https://docs.codecov.com/docs/quick-start#step-4-upload-coverage-reports-to-codecov) is about using a github action**

In practice, this can be summarized as something like this:

```yaml
  - run: pytest --cov .
  - uses: codecov/codecov-action@v3
```

**[Step 5](https://docs.codecov.com/docs/quick-start#step-5-get-coverage-analysis-from-codecov)** is describing how coverage information now is presented

- The GitHub Workflow job's step emits output
- There should be two PR status checks (codecov/patch, codecov/project)
- And a pull request comment from a codecov bot

**[Step 6](https://docs.codecov.com/docs/quick-start#step-6-view-the-dashboard-on-codecov)** About viewing a dashboard on codecov's website

### Conclusion on setting up codecov

To setup codecov for our public repos, I think the only thing individual repo's needs to do is to:

1. Install `pytest-cov` as a test dependency
2. Run `pytest` with `--cov`
3. Run the codecov/codecov-action@v3 github action in a final step in a github workflow's job

**Comment by sgibson91** [comment]
Codecov is a service that reports coverage of tests, and in PRs will provide feedback (in a comment) on whether coverage increases or decreases with the changes made. I've implemented it on a few of my personal projects. Whether we implement it as default or not I think depends on how strict we want to be about test coverage. For example, you can set rules that prevent PRs from being merged if they cause test coverage to decrease. I do not recommend we do that (too much maintenance for a volunteer team). I think the big question here is: Does this provide value? Knowing about test coverage of a package, especially in PRs, could be helpful in ensuring all incoming code has tests. It could also be a cause of noise with PR comments (though once the comment is made, it is updated with every subsequent push).

I believe Sheila's question is regarding whether she has the permissions to install the [Codecov app](https://github.com/apps/codecov) onto the GitHub repo she's working in. And I think even if she doesn't, she should be able to request it to be approved by an org admin?

**Comment by sgibson91** [comment]
> by looking at some specific metric etc?

The metric it uses is "lines of source code executed when the test suite is run". So from the below screenshot from one of my personal projects, you can see >=95% of the code in 3/5 files in the package are executed via tests.

<img width="803" alt="Screenshot 2023-04-14 at 13 32 44" src="https://user-images.githubusercontent.com/44771837/232044460-d5ae87f5-b17f-4a9f-aa9d-ba0f1aff7ab0.png">

I don't think this is a perfect metric. It pushes people to write more tests that cover more code, and doesn't highlight the nuance in things like the reliability or quality of a test, some lines of code just don't need testing (print statements, imports, whatever), or that it's just impractical to test some lines of code. For example in the screenshot above, the `main.py` file has the lowest coverage. That's because it's job is mostly to call all the other functions and classes in the other files, which are already covered by their individual unit tests. To test the functions in `main.py`, I'd have to monkey patch so many things to avoid actual external calls to APIs, etc, and it wouldn't provide me with more information than the unit tests for the bulk of the code already do. So I live life with low coverage in that file 😆

**Comment by minrk** [comment]
I think coverage is a fairly noisy signal. That's why I don't like codecov _comments_ or CI status requirements (our repos generally have a threshold of 0% - so all they really provide are a link to view coverage reports). But I think it's handy to have that link that can quickly say "which parts of this have I exercised in my tests?". I think it's most useful when writing or reviewing _larger_ PRs, especially with complex or numerous conditions, so I can check which parts have been exercised in the tests.

I don't have a strong preference for adding it systematically, vs letting people add it when they feel like it.

> I believe Sheila's question is regarding whether she has the permissions to install the [Codecov app](https://github.com/apps/codecov) onto the GitHub repo

It already has access to all jupyterhub repos, so I don't think there's anything to set up. It should Just Work® if codecov starts uploading for the repo.

**Comment by consideRatio** [comment]
I ended up bundling multiple questions and answering parts myself in this issue.

1. Question about how we use codecov, and what we want for new projects etc?
2. Question on how to setup codecov practically (answered in conclusion of https://github.com/jupyterhub/team-compass/issues/640#issuecomment-1508349990, it seems trivial)

Thank you for providing examples of usage @sgibson91! I looked into codecov myself now and concluded that its quite nice to see exactly what lines of code is covered or not as a followup.

For example I can easily see what lines of code are called, and that is a great followup on the summarizing metrics.

![image](https://user-images.githubusercontent.com/3837114/232047354-5de32cf2-091a-473c-b7a5-a5688912f8af.png)

Okay so codecov/patch metric showing 100% means that all new lines of code in a PR is tested, and if it shows 0% means that new lines in a PR wasn't executed when `pytest` ran - right?

I'm starting to opinionate towards a big :+1: for adopting this by default in new projects, but perhaps prefer to see no comments be posted or a requirement set on test coverage be enforced.

Ah I now see from https://app.codecov.io/account/gh/jupyterhub/yaml that there is a global setting to configure codecov to not post comments by default, or enforce patch coverage etc - nice!

@sgibson91 I invited you to be able to admin the codecov settings btw!

**Comment by choldgraf** [comment]
One thing I'll note, and that has been an annoyance of codecov in other projects I'm on over the years, is that codecov itself can be unreliable. Sometimes the service just ... doesn't work . I think this is because of github rate limits and the codecov service. This becomes really annoying if codecov is ever a blocker to merging or making releases. So if codecov is broadly adopted, I suggest not putting it on the critical path to merge.

**Comment by minrk** [comment]
Yeah, several of my colleagues have been working on getting GitHub actions to merge and display coverage in the GHA summary because codecov's become less reliable (easily merging coverage reports from parametrized runs, even on multiple CI providers is the best part of codecov). They are still a bit of a pain to set up, which is why I currently still lean _slightly_ toward codecov as a low-priority low-effort signal that I don't need to trust to be rigorous. If folks want to integrate coverage more thoroughly into their workflow, a different approach is needed.

**Comment by sgibson91** [comment]
> Sometimes the service just ... doesn't work

Yeah, I often end up re-running failed jobs because the upload to codecov step failed.

**Comment by manics** [comment]
Has anyone tried codecov with GitHub annotations?
https://docs.codecov.com/docs/github-checks

I've only just found out about it. I think it's less noisy than comments (AFAIK annotations won't generate notifications) whilst providing visibility when reviewing a PR. I almost never look at codecov when reviewing JupyterHub PRs, mostly because if the GH CI status is green for all checks I assume there's nothing to look at. If it's something we should consider when reviewing PRs I think it'd be good to add it to https://jupyterhub-team-compass.readthedocs.io/en/latest/practices/pull_requests.html#what-to-look-for-when-reviewing

**Comment by consideRatio** [comment]
> Yeah, I often end up re-running failed jobs because the upload to codecov step failed.

I figure we can add `continue-on-error: true` to the codecov action step if its intermittently failing. I recall issues, but it was quite a while since the last issue.

---

I more freshly recall issues is when a PR status check is reported as failing, but I think I associate such events with repo's enforcing testing code coverage only. I also think this can happen if we have multiple test jobs running tests variations, then codecov may report a failure if it has only received a report from one of the test jobs but not all yet. I think that was confusing noise as well, hard to separate from "all tests completed and successfully reported something, but test coverage wasn't sufficient".

> Has anyone tried codecov with GitHub annotations?
https://docs.codecov.com/docs/github-checks

I recall something that I found to be horribly intrusive, making either PRs review or test job runs hard to read - I don't remember which, but I have a big red flag in my memory associated with this now.

**Comment by consideRatio** [comment]
Thank you all for the quick discussion about this. To me, this issue can be closed at this point and here are my takeaways.

### Takeaway points

- [github.com/jupyterhub has approved integration with codecov for all repos](https://github.com/organizations/jupyterhub/settings/installations/266222), so setting it up in an individual repo is as easy as: a) installing `pytest-cov` as a test dependency, b) adding `--cov` to the `pytest` command, c) running the `codecov/codecov-action@v3` github action without additional arguments.
- As a team we seem fine with seeing projects setup like above but want to minimize noise. For this purpose, codecov [is configured for the jupyterhub github org](https://app.codecov.io/account/gh/jupyterhub/yaml) to not provide a comment and will approve any coverage report - even 0%.
- Anyone can visit and inspect, without needing to login, reported code test coverage reports at https://app.codecov.io/gh/jupyterhub for our projects. There, anyone can learn what is being tested and not, and help improve test coverage. Anyone can also press the codecov/patch status check in PRs that has reported coverage, and use it during the PR review or authoring process.
