### ISSUE TITLE
Don't make pre-commit.ci mandatory on JupyterHub repos

### ISSUE THREAD

**Issue by manics** [jupyterhub/team-compass#697]
I think (though don't have access to check) that pre-commit.ci has been turned on for all JupyterHub repos. This is based on seeing recent PRs in repos that don't have a `.pre-commit-config.yaml` file showing a failed pre-commit.ci GitHub status.

I don't think it should be a blanket requirement for all repos to require pre-commit, especially those that aren't using Python.

**Comment by consideRatio** [comment]
I agree that since pre-commit.ci makes it error when we don't have a pre-commit-config.yaml file, we should enable pre-commit.ci one repo at the time instead.

[According to audit logs](https://github.com/organizations/jupyterhub/settings/audit-log?q=action%3Aintegration_installation.repositories_added+) the pre-commit.ci was added for all repos October 30 by @minrk. @minrk I've added back all repo's that via search had a `.pre-commit-config.yaml` file so that we don't get test failures to show up due to a missing pre-commit-config.yaml file for now. Is that okay?

**Comment by consideRatio** [comment]
@manics I think you should have access, you are listed as an Owner of the JupyterHub org. Look under the jupyterhub orgs settings -> GitHub Apps -> pre-commit.ci (Configure): https://github.com/organizations/jupyterhub/settings/installations/17782968

**Comment by manics** [comment]
Thanks for sorting it out!

**Comment by minrk** [comment]
Yeah, sorry about that. I figured it would only run if the config file was there, like most other services. Definitely don't mean to enforce it on everyone, just wanted to make it easier to adopt.
