### ISSUE TITLE
SciPy Jupyter plenary project updates

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#731]
There's going to be a very brief Tools Plenary update at SciPy (https://github.com/jupyter/governance/issues/233), and we've been asked for any highlights from JupyterHub we'd like mentioned.

Anyone have things they'd like highlighted? I think we're talking about one very high level slide for all of JupyterHub, so really quick mentions of releases or ongoing/upcoming activities we'd like raised.

The main thing for me would probably be JupyterHub 5 with user-initiated sharing. Any z2jh/oauthenticator/repo2docker/binder highlights folks would like to bring to a general SciPy audience? We need updates by EOD US tomorrow (Thursday). Sorry for late notice, I'm AFK most of this month and not checking email every day.

cc @ivanov

**Comment by manics** [comment]
The JupyterHub org has [89 PRs with `label:new` merged since 2023-01-01](https://github.com/search?q=org%3Ajupyterhub+type%3Apr+merged%3A%3E2023-01-01+label%3Anew&type=pullrequests), and [84 PRs with `label:enhancement` merged since 2023-01-01](https://github.com/search?q=org%3Ajupyterhub+type%3Apr+merged%3A%3E2023-01-01+label%3Aenhancement&type=pullrequests)

A few things that stood out for me from those results, though I'm not sure if these are all worth highlighting:
- Adding windows support to simpervisor https://github.com/jupyterhub/simpervisor/pull/26 , which means https://github.com/mathworks/jupyter-matlab-proxy can run on Windows
- jupyter-remote-desktop-proxy had a UI update https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/78 , you could liven up a potentially text heavy slide by using the desktop screenshot
- repo2docker update to JupyterLab 4 https://github.com/jupyterhub/repo2docker/pull/1340

It'd also be nice to acknowledge Curvenote's support of mybinder.org this year.
