### ISSUE TITLE
Build Docker Images of Repos for Demos @ NeurIPS

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/team-compass#85]
See #52

**Comment by betatim** [comment]
What do we want to persuade people off with the demo? Trying to nail that down will help pick repositories that help with that.

I think we should work/demonstrate/let people know that using GPUs with BinderHub is simple and "just works". For the demo stand where people wander past I think having something that makes that point in less than 60s is going to be good. Maybe being able to show:
* here the a repo not using GPU support and while that runs;
* "look at the diff" to get GPU support
* now look over here "doesn't it run fast with GPU support?"

so people can see how little work it is and that indeed the GPU one runs much faster.

Once we have something like this I'd branch out to more "real world" repos and try and get them to run. I'd expect us the have quite a bit of work there just because scientific code takes forever to get running (precisely what we want to fix :) )

**Comment by jzf2101** [comment]
The following are already on binder: 
- [ ] https://github.com/davidmascharka/tbd-nets
 - [ ] https://github.com/dtak/rrr
-  [ ] https://github.com/ray-project/tutorial
-  [ ] https://github.com/jrzech/reproduce-chexne

This one would be useful to include:
- [ ] https://github.com/harvardnlp/annotated-transformer (using a fork)
- [ ] https://github.com/slundberg/shap (not all demos work)
- [ ] https://github.com/FluxML/model-zoo
- [ ]  https://github.com/rgiordan/LinearResponseVariationalBayesNIPS2015
- [ ] https://github.com/flow-project/flow/tree/master/tutorials/

**Comment by choldgraf** [comment]
maybe a relevant post I saw in @psychemedia 's newsletter: https://negativesign.com/blog/2018/11/11/docker-and-jupyterhub-for-deep-learning/

**Comment by jzf2101** [comment]
Also https://github.com/whlteXbread/GPU-Jupyterhub

**Comment by jzf2101** [comment]
@cmd-rtf do you haver any suggestions?

**Comment by consideRatio** [comment]
@jzf2101 No concrete answer here. But, if there would be a paper that is reproducible (or could be made so with some help), and that also has been showcased in the excellent youtube channel *2minutepapers*, it would certainly make me really curious to run myself.

**Comment by cmd-ntrf** [comment]
The notebooks from the fast.ai course could be a good start:
https://github.com/fastai/course-v3

We could probably reach to Jeremy Howard on Twitter and see if he has suggestions of other notebooks that could be cool to demo.

**Comment by cmd-ntrf** [comment]
I have also downloaded every papers from this year and last year, and I am currently pdfgrepping to see if any mentions notebook or jupyter.

**Comment by jzf2101** [comment]
Awesome!

**Comment by choldgraf** [comment]
Also note there are a lot of interesting repositories usable w/ binder shown here: https://discourse.jupyter.org/t/share-your-binder/32/7

**Comment by jzf2101** [comment]
Thanks!  I was going to get some stuff I know works from the binder ecosystem up and going- don't think we need to rebuild them because they're already good to go 

I'd like to iron out the details of the nodepool situation to get the CUDA stuff out the door.

**Comment by jzf2101** [comment]
Stuff built on the neurips binder:

- github.com/jzf2101/tutorial/tree/gpu-binder
- github.com/jzf2101/GAN-tutorial/tree/gpu-binder
- github.com/jzf2101/shap/tree/gpu-binder

**Comment by consideRatio** [comment]
If we directlink, perhaps we should provide an `?urlpath=lab` in these links after all? The drawbacks of using jupyterlab were mainly because of the interface on the landing page and that is bypassed with a directlink.

To me and my collegues working with Jupyter, the key argument for using the platform i have deployed vs using google colaboratory is that my deployment supports jupyterlab, and colaboratory does not and is stuck in the old age.

@minrk @betatim do think its a no go with lab for direct links as well?

**Comment by minrk** [comment]
Direct links with lab are fine with me, but I probably wouldn't change anything more today.

**Comment by choldgraf** [comment]
hey all - what's a thing that we can quickly do to check that the GPUs etc are working? I tried one of @jzf2101 's repositories and it wasn't able to download the MNIST data due to "temporary error in name resolution" but I mostly just wanna check that the GPUs are working etc :-)

**Comment by betatim** [comment]
We seem to have broken network access for the moment. Erik is working on it, next update on the hour. GPUs seem to be working, the more basic "internet access" probably got broken by changing things to close to the "going live" moment.

**Comment by consideRatio** [comment]
Everything is broke after hard-to-debug issues caused by quota-limits on CPU / storage etc.

They are lifted now, and we can get things going i think, but operations are not superquick.

**Comment by choldgraf** [comment]
:-) ok well I am going to run to the printer to print [our lovely poster that @jzf2101 made](https://docs.google.com/presentation/d/1N97dNH2jmvPn9fzEyrnv6rkk-2e9XNilizHCfR0nsC8/edit?ts=5c066571#slide=id.gcb9a0b074_1_0) a full 1 hour before our demonstration begins. We decided to give ourselves an hour of padding because, you know, we didn't want to cut it too close :-)

**Comment by cmd-ntrf** [comment]
Let me know when things are back and working. I'll test the links Jessica provided while Chris is running to print the poster.

**Comment by consideRatio** [comment]
@cmd-ntrf will do

**Comment by betatim** [comment]
We should be back in business @choldgraf @jzf2101 and @cmd-ntrf 

Just launched github.com/jzf2101/GAN_tutorial/tree/gpu-binder [![Binder](https://neurips.mybinder.org/badge_logo.svg)](https://neurips.mybinder.org/v2/gh/jzf2101/GAN_tutorial/gpu-binder?urlpath=lab) which works now.

**Comment by cmd-ntrf** [comment]
I confirm that it is working. I am currently at Epoch 10 GAN tutorial and it is running smoothly.

Good job!

**Comment by consideRatio** [comment]
@jzf2101 the risk of memory issues is now a lot lower, you can peak to 20 GB while it was 11 GB before. If things go down now, it is probably due to the GPU running out of memory with its 12GB.

**Comment by choldgraf** [comment]
fyoooo back at the airbnb after the demos. Just want to say thanks again to you all for helping get this thing working and keeping an eye on it during the demo. Much much <3 for all of your awesome help, it's what I love most about the jupyterhub community!

**Comment by jzf2101** [comment]
Great job everyone! 🎉
